sudo: required
services:
  - docker

before_install:
  - docker build -t annamreich/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true annamreich/react-test npm test

after_success:
  - docker build -t annamreich/multi-client ./client
  - docker build -t annamreich/multi-nginx ./nginx
  - docker build -t annamreich/multi-server ./server
  - docker build -t annamreich/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push annamreich/multi-nginx
  - docker push annamreich/multi-server
  - docker push annamreich/multi-worker 
  - docker push annamreich/multi-client